### ISSUE TITLE
Speedup docker image build time

### ISSUE THREAD

**Issue by JBerny** [robertoschiavone/crocodile#1]
The crocodile docker image uses multiple `RUN` commands to install apt packages. All those can be merged into one to reduce the nr. of overlayfs layers and to let apt do all the installs in one go.

**Comment by robertoschiavone** [comment]
I know it's inefficient, but this way each `RUN` layer is cached separately so that every time it doesn't reinstall all the packages. Besides, packages are sorted alphabetically and I find it easier to maintain the image by adding/removing them this way.
